[General]
;DLLName=E:\AI\LLLAMA\A3\cp\ggml-base.dll
DLLName=D:\Projet\Delphi\DXE\GGUFEdit\32\ggml-base.dll
TypeCount=42

[Types]
0=F32
1=F16
2=Q4_0
3=Q4_1
4=Q4_2
5=Q4_3
6=Q5_0
7=Q5_1
8=Q8_0
9=Q8_1
10=Q2_K
11=Q3_K
12=Q4_K
13=Q5_K
14=Q6_K
15=Q8_K
16=IQ2_XXS
17=IQ2_XS
18=IQ3_XXS
19=IQ1_S
20=IQ4_NL
21=IQ3_S
22=IQ2_S
23=IQ4_XS
24=I8
25=I16
26=I32
27=I64
28=F64
29=IQ1_M
30=BF16
31=Q4_0_4_4
32=Q4_0_4_8
33=Q4_0_8_8
34=TQ1_0
35=TQ2_0
36=IQ4_NL_4_4
37=IQ4_NL_4_8
38=IQ4_NL_8_8
39=MXFP4
40=NVFP4
41=Q1_0

[ScalarSizes]
0=4
1=2
24=1
25=2
26=4
27=8
28=8
30=2

[IsQuant]
0=0;F32
1=0;F16
2=1;Q4_0
3=1;Q4_1
4=1;Q4_2
5=1;Q4_3
6=1;Q5_0
7=1;Q5_1
8=1;Q8_0
9=1;Q8_1
10=1;Q2_K
11=1;Q3_K
12=1;Q4_K
13=1;Q5_K
14=1;Q6_K
15=1;Q8_K
16=1;IQ2_XXS
17=1;IQ2_XS
18=1;IQ3_XXS
19=1;IQ1_S
20=1;IQ4_NL
21=1;IQ3_S
22=1;IQ2_S
23=1;IQ4_XS
24=0;I8
25=0;I16
26=0;I32
27=0;I64
28=0;F64
29=IQ1_M
30=0;BF16
31=1;Q4_0_4_4
32=1;Q4_0_4_8
33=1;Q4_0_8_8
34=1;TQ1_0
35=1;TQ2_0
36=1;IQ4_NL_4_4
37=1;IQ4_NL_4_8
38=1;IQ4_NL_8_8
39=1;MXFP4
40=1;NVFP4
41=1;Q1_0

[BlockElems]
2=32
3=32
6=32
7=32
8=32
9=32
10=256
11=256
12=256
13=256
14=256
15=256
16=256
17=256
18=256
19=256
20=32
21=256
22=256
23=256
34=256
35=256
39=32
40=64
41=128

[BlockBytes]
2=18
3=20
6=22
7=24
8=34
9=36
10=84
11=110
12=144
13=176
14=210
15=258
16=66
17=74
18=98
19=50
20=18
21=110
22=72
23=136
34=54
35=66
39=17
40=36
41=18

[DLLFunctions]
RowSize=ggml_row_size
; Mappings de déquantisation (Dequant)
Dequant.0=ggml_fp16_to_fp32_row
Dequant.1=ggml_fp16_to_fp32_row
Dequant.2=dequantize_row_q4_0
Dequant.3=dequantize_row_q4_1
Dequant.6=dequantize_row_q5_0
Dequant.7=dequantize_row_q5_1
Dequant.8=dequantize_row_q8_0
Dequant.9=dequantize_row_q8_1
Dequant.10=dequantize_row_q2_K
Dequant.11=dequantize_row_q3_K
Dequant.12=dequantize_row_q4_K
Dequant.13=dequantize_row_q5_K
Dequant.14=dequantize_row_q6_K
Dequant.15=dequantize_row_q8_K
Dequant.16=dequantize_row_iq2_xxs
Dequant.17=dequantize_row_iq2_xs
Dequant.18=dequantize_row_iq3_xxs
Dequant.19=dequantize_row_iq1_s
Dequant.20=dequantize_row_iq4_nl
Dequant.21=dequantize_row_iq3_s
Dequant.22=dequantize_row_iq2_s
Dequant.23=dequantize_row_iq4_xs
Dequant.29=dequantize_row_iq1_m
Dequant.30=ggml_bf16_to_fp32_row
Dequant.34=dequantize_row_tq1_0
Dequant.35=dequantize_row_tq2_0
Dequant.39=dequantize_row_mxfp4
Dequant.40=dequantize_row_nvfp4
Dequant.41=dequantize_row_q1_0

; Mappings de quantisation (Quant)
Quant.0=ggml_fp32_to_fp16_row
Quant.1=ggml_fp32_to_fp16_row
Quant.2=quantize_q4_0
Quant.3=quantize_q4_1
Quant.6=quantize_q5_0
Quant.7=quantize_q5_1
Quant.8=quantize_q8_0
;Quant.9=quantize_row_q8_1_ref
Quant.10=quantize_q2_K
Quant.11=quantize_q3_K
Quant.12=quantize_q4_K
Quant.13=quantize_q5_K
Quant.14=quantize_q6_K
;Quant.15=quantize_row_q8_K_ref
;Quant.16=quantize_iq2_xxs
Quant.17=quantize_iq2_xs
Quant.18=quantize_iq3_xxs
Quant.19=quantize_iq1_s
Quant.20=quantize_iq4_nl
Quant.21=quantize_iq3_s
Quant.22=quantize_iq2_s
Quant.23=quantize_iq4_xs
Quant.29=quantize_iq1_m
Quant.30=ggml_fp32_to_bf16_row
Quant.34=quantize_tq1_0
Quant.35=quantize_tq2_0
Quant.39=quantize_mxfp4
Quant.40=quantize_nvfp4
Quant.41=quantize_q1_0
